"""Regenerate the attributed synthetic replay manifest; no physical target access."""

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from fixtures.synthetic import segments

root = Path(__file__).resolve().parents[1]
profile = json.loads((root / "config/demo.json").read_text())
manifest = {
    "provenance": "Synthetic fixture v1, generated by scripts/make_replay.py; NOT a physical capture",
    "captured_at": "2026-09-22T00:00:00+00:00",
    "profile": profile,
    "registers": {"pc": 0x80000000, "lr": 0x80000008, "sp": 0x800011F0, "cpsr": 19},
    "segments": [
        {"address": a, "hex": bytes(d).hex(), "sha256": hashlib.sha256(d).hexdigest()}
        for a, d in segments().items()
    ],
}
(root / "fixtures/replay.json").write_text(json.dumps(manifest, indent=2) + "\n")
