/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_runs__rid__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_runs__rid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{rid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_runs__rid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{rid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_runs__rid__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{rid}/report.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Json Report */
        get: operations["json_report_api_runs__rid__report_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{rid}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Md Report */
        get: operations["md_report_api_runs__rid__report_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/target/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_v1_target_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/target/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_target_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session */
        post: operations["session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read */
        post: operations["read_api_v1_memory_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registers/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registers */
        post: operations["registers_api_v1_registers_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot */
        post: operations["snapshot_api_v1_snapshots_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/target/halt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Halt */
        post: operations["halt_api_v1_target_halt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/target/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_target_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/target/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step */
        post: operations["step_api_v1_target_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write */
        post: operations["write_api_v1_memory_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditRequest */
        AuditRequest: {
            /** Target Id */
            target_id: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "firmware triage" | "bootloader inspection" | "crash investigation";
            /** Region Names */
            region_names: string[];
            /**
             * Byte Budget
             * @default 16384
             */
            byte_budget: number;
            /**
             * Collection Limit
             * @default 12
             */
            collection_limit: number;
            /**
             * Iteration Limit
             * @default 4
             */
            iteration_limit: number;
            /**
             * Deadline Seconds
             * @default 120
             */
            deadline_seconds: number;
        };
        /** EvidenceBundle */
        EvidenceBundle: {
            /** Evidence Id */
            evidence_id: string;
            /** Base Address */
            base_address: number;
            /** Length */
            length: number;
            /** Content Hash */
            content_hash: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "mock" | "replay" | "openocd";
            /** Provenance */
            provenance: string;
            /**
             * Architecture
             * @default arm
             */
            architecture: string;
            /** Endianness */
            endianness: string;
            /** Instruction Mode */
            instruction_mode: string;
            /** Settings Source */
            settings_source: string;
            /** Decoder */
            decoder: string;
            /**
             * Strings
             * @default []
             */
            strings: components["schemas"]["StringObservation"][];
            /**
             * Instructions
             * @default []
             */
            instructions: components["schemas"]["Instruction"][];
            /** Approved Hex */
            approved_hex?: string | null;
            /** Withheld Reason */
            withheld_reason?: string | null;
            /**
             * Uncertainties
             * @default []
             */
            uncertainties: string[];
        };
        /** Finding */
        Finding: {
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "observation" | "hypothesis" | "vulnerability";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Status
             * @enum {string}
             */
            status: "observed" | "suspected" | "validated" | "inconclusive" | "rejected";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Addresses */
            addresses: number[];
            /** Explanation */
            explanation: string;
            /** Limitations */
            limitations: string[];
            /** Suggested Verification */
            suggested_verification: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Instruction */
        Instruction: {
            /** Address */
            address: number;
            /** Size */
            size: number;
            /** Mnemonic */
            mnemonic: string;
            /** Operands */
            operands: string;
        };
        /** Login */
        Login: {
            /** Password */
            password: string;
        };
        /** MemoryReadResult */
        MemoryReadResult: {
            /** Requested Length */
            requested_length: number;
            /** Returned Length */
            returned_length: number;
            /** Base Address */
            base_address: number;
            /** Address Space */
            address_space: string;
            /** Evidence Id */
            evidence_id: string;
            /** Content Hash */
            content_hash: string;
            /** Timestamp */
            timestamp?: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "mock" | "replay" | "openocd";
            /** Target State */
            target_state: string;
            /** Generation */
            generation: number;
            /** Partial */
            partial: boolean;
            /** Consistency */
            consistency: string;
            evidence: components["schemas"]["EvidenceBundle"];
        };
        /** ReadProposal */
        ReadProposal: {
            /** Address */
            address: number;
            /**
             * Length
             * @default 256
             */
            length: number;
            /**
             * Address Space
             * @default virtual
             * @enum {string}
             */
            address_space: "virtual" | "physical";
            /** Reason */
            reason: string;
        };
        /** Region */
        Region: {
            /** Name */
            name: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ram" | "rom";
            /**
             * Address Space
             * @default virtual
             * @enum {string}
             */
            address_space: "virtual" | "physical";
            /**
             * Executable
             * @default false
             */
            executable: boolean;
            /**
             * Instruction Mode
             * @default arm
             * @enum {string}
             */
            instruction_mode: "arm" | "thumb";
            /**
             * Approved
             * @default true
             */
            approved: boolean;
        };
        /** RegisterSnapshot */
        RegisterSnapshot: {
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Timestamp */
            timestamp?: string;
            /** Evidence Id */
            evidence_id?: string;
            /** Target State */
            target_state: string;
            /** Generation */
            generation: number;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "mock" | "replay" | "openocd";
            /**
             * Mode Information
             * @default Profile mode; CPSR evidence is not an automatic override
             */
            mode_information: string;
        };
        /** RunState */
        RunState: {
            /** Run Id */
            run_id?: string;
            /**
             * Status
             * @default queued
             */
            status: string;
            /**
             * Target Backend
             * @enum {string}
             */
            target_backend: "mock" | "replay" | "openocd";
            /**
             * Inference Backend
             * @enum {string}
             */
            inference_backend: "scripted" | "nebius";
            /** Model Id */
            model_id: string;
            profile: components["schemas"]["TargetProfile"];
            request: components["schemas"]["AuditRequest"];
            /** Created At */
            created_at?: string;
            /**
             * Captures
             * @default []
             */
            captures: components["schemas"]["MemoryReadResult"][];
            /**
             * Registers
             * @default []
             */
            registers: components["schemas"]["RegisterSnapshot"][];
            /**
             * Visited Regions
             * @default []
             */
            visited_regions: string[];
            /**
             * Plan
             * @default []
             */
            plan: components["schemas"]["ReadProposal"][];
            /**
             * Findings
             * @default []
             */
            findings: components["schemas"]["Finding"][];
            /**
             * Events
             * @default []
             */
            events: {
                [key: string]: unknown;
            }[];
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Bytes Requested
             * @default 0
             */
            bytes_requested: number;
            /**
             * Collection Actions
             * @default 0
             */
            collection_actions: number;
            /**
             * Analysis Iterations
             * @default 0
             */
            analysis_iterations: number;
            /** Termination Reason */
            termination_reason?: string | null;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Tool Latencies Ms
             * @default []
             */
            tool_latencies_ms: number[];
            /**
             * Inference Latencies Ms
             * @default []
             */
            inference_latencies_ms: number[];
            /**
             * Provider Usage
             * @default []
             */
            provider_usage: {
                [key: string]: unknown;
            }[];
        };
        /** StringObservation */
        StringObservation: {
            /** Address */
            address: number;
            /** Offset */
            offset: number;
            /** Text */
            text: string;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
        };
        /** TargetProfile */
        TargetProfile: {
            /** Target Id */
            target_id: string;
            /**
             * Architecture
             * @default arm
             * @constant
             */
            architecture: "arm";
            /**
             * Endianness
             * @default little
             * @enum {string}
             */
            endianness: "little" | "big";
            /**
             * Address Width
             * @default 32
             * @constant
             */
            address_width: 32;
            /**
             * Address Spaces
             * @default [
             *       "virtual"
             *     ]
             */
            address_spaces: ("virtual" | "physical")[];
            /** Regions */
            regions: components["schemas"]["Region"][];
            /**
             * Registers
             * @default [
             *       "pc",
             *       "lr",
             *       "sp",
             *       "cpsr"
             *     ]
             */
            registers: string[];
            /**
             * Capabilities
             * @default [
             *       "read",
             *       "registers",
             *       "snapshot"
             *     ]
             */
            capabilities: ("read" | "registers" | "snapshot" | "halt" | "resume" | "step" | "write")[];
            /** Provenance */
            provenance: string;
            /**
             * Verified For Live
             * @default false
             */
            verified_for_live: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** MemoryReadRequest */
        MemoryReadRequest: {
            /** Target Id */
            target_id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id?: string;
            /** Expected Generation */
            expected_generation?: number | null;
            /** Address */
            address: number;
            /**
             * Length
             * @default 256
             */
            length: number;
            /**
             * Address Space
             * @default virtual
             * @enum {string}
             */
            address_space: "virtual" | "physical";
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Target Id */
            target_id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id?: string;
            /** Expected Generation */
            expected_generation?: number | null;
            /**
             * Names
             * @default [
             *       "pc",
             *       "lr",
             *       "sp",
             *       "cpsr"
             *     ]
             */
            names: string[];
        };
        /** SessionRequest */
        SessionRequest: {
            /** Target Id */
            target_id: string;
            /**
             * Operations
             * @default [
             *       "read",
             *       "registers",
             *       "snapshot"
             *     ]
             */
            operations: ("read" | "registers" | "snapshot" | "halt" | "resume" | "step" | "write")[];
            /** Regions */
            regions: components["schemas"]["Region"][];
            /**
             * Byte Budget
             * @default 16384
             */
            byte_budget: number;
            /**
             * Operation Limit
             * @default 24
             */
            operation_limit: number;
            /**
             * Ttl Seconds
             * @default 120
             */
            ttl_seconds: number;
        };
        /** SnapshotRequest */
        SnapshotRequest: {
            /** Target Id */
            target_id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id?: string;
            /** Expected Generation */
            expected_generation?: number | null;
            /** Address */
            address: number;
            /**
             * Length
             * @default 256
             */
            length: number;
            /**
             * Address Space
             * @default virtual
             * @enum {string}
             */
            address_space: "virtual" | "physical";
            /**
             * Registers
             * @default [
             *       "pc",
             *       "lr",
             *       "sp",
             *       "cpsr"
             *     ]
             */
            registers: string[];
        };
        /** TargetRequest */
        TargetRequest: {
            /** Target Id */
            target_id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id?: string;
            /** Expected Generation */
            expected_generation?: number | null;
        };
        /** ToolResult */
        ToolResult: {
            /** Success */
            success: boolean;
            /** Request Id */
            request_id: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error Code */
            error_code?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Provenance */
            provenance: string;
            /**
             * Outcome Uncertain
             * @default false
             */
            outcome_uncertain: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** WriteRequest */
        WriteRequest: {
            /** Target Id */
            target_id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id?: string;
            /** Expected Generation */
            expected_generation?: number | null;
            /** Address */
            address: number;
            /**
             * Length
             * @default 256
             */
            length: number;
            /**
             * Address Space
             * @default virtual
             * @enum {string}
             */
            address_space: "virtual" | "physical";
            /** Data Hex */
            data_hex: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_runs__rid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_runs__rid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_runs__rid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_runs__rid__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    json_report_api_runs__rid__report_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    md_report_api_runs__rid__report_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_v1_target_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_target_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_memory_read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registers_api_v1_registers_read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_v1_snapshots_capture_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    halt_api_v1_target_halt_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_target_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_api_v1_target_step_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_api_v1_memory_write_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
